openapi: 3.0.1
info:
  title: untitled API
  version: "536"
servers:
- url: /
paths:
  /{apiVersion}/client_config:
    get:
      operationId: GetClientConfig
      parameters:
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetClientConfig_200_Response'
      summary: GetClientConfig
  /{apiVersion}/reg:
    post:
      operationId: Register
      parameters:
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register_Request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register_200_Response'
      summary: Register
  /{apiVersion}/reg/{sourceDeviceId}:
    get:
      operationId: GetSourceDevice
      parameters:
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: sourceDeviceId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSourceDevice_200_Response'
      summary: GetSourceDevice
    patch:
      operationId: UpdateSourceDevice
      parameters:
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: sourceDeviceId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSourceDevice_Request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSourceDevice_200_Response'
      summary: UpdateSourceDevice
  /{apiVersion}/reg/{sourceDeviceId}/account:
    get:
      operationId: GetAccount
      parameters:
      - explode: false
        in: path
        name: sourceDeviceId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAccount_200_Response'
      summary: GetAccount
    put:
      operationId: UpdateAccount
      parameters:
      - explode: false
        in: path
        name: sourceDeviceId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccount_Request'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAccount_200_Response'
      summary: UpdateAccount
  /{apiVersion}/reg/{sourceDeviceId}/account/devices:
    get:
      operationId: GetBoundDevices
      parameters:
      - explode: false
        in: path
        name: sourceDeviceId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/GetBoundDevices_200_Response'
                type: array
      summary: GetBoundDevices
  /{apiVersion}/reg/{sourceDeviceId}/account/license:
    post:
      operationId: ResetAccountLicense
      parameters:
      - explode: false
        in: path
        name: sourceDeviceId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetAccountLicense_200_Response'
      summary: ResetAccountLicense
  /{apiVersion}/reg/{sourceDeviceId}/account/reg/{boundDeviceId}:
    patch:
      operationId: UpdateBoundDevice
      parameters:
      - explode: false
        in: path
        name: sourceDeviceId
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: apiVersion
        required: true
        schema:
          type: string
        style: simple
      - explode: false
        in: path
        name: boundDeviceId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateBoundDevice_Request'
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UpdateBoundDevice_200_Response'
                type: array
      summary: UpdateBoundDevice
components:
  schemas:
    GetAccount_200_Response:
      example:
        license: license
        referral_count: 1.4658129805029452
        account_type: account_type
        role: role
        referral_renewal_countdown: 5.962133916683182
        created: created
        quota: 6.027456183070403
        warp_plus: true
        premium_data: 0.8008281904610115
        id: id
        updated: updated
      properties:
        account_type:
          type: string
        created:
          type: string
        id:
          type: string
        license:
          type: string
        premium_data:
          type: number
        quota:
          type: number
        referral_count:
          type: number
        referral_renewal_countdown:
          type: number
        role:
          type: string
        updated:
          type: string
        warp_plus:
          type: boolean
      required:
      - account_type
      - created
      - id
      - license
      - premium_data
      - quota
      - referral_count
      - referral_renewal_countdown
      - role
      - updated
      - warp_plus
      type: object
    GetBoundDevices_200_Response:
      example:
        role: role
        created: created
        name: name
        active: true
        model: model
        id: id
        type: type
        activated: activated
      properties:
        activated:
          type: string
        active:
          type: boolean
        created:
          type: string
        id:
          type: string
        model:
          type: string
        name:
          type: string
        role:
          type: string
        type:
          type: string
      required:
      - activated
      - active
      - created
      - id
      - model
      - role
      - type
      type: object
    GetClientConfig_200_Response:
      example:
        captive_portal:
        - name: name
          networks:
          - address: address
          - address: address
        - name: name
          networks:
          - address: address
          - address: address
        denylist:
        - visible: true
          name: name
          networks:
            v6:
            - address: address
              prefix: 0.8008281904610115
            - address: address
              prefix: 0.8008281904610115
            v4:
            - address: address
              netmask: netmask
            - address: address
              netmask: netmask
          android-packages:
          - android-packages
          - android-packages
        - visible: true
          name: name
          networks:
            v6:
            - address: address
              prefix: 0.8008281904610115
            - address: address
              prefix: 0.8008281904610115
            v4:
            - address: address
              netmask: netmask
            - address: address
              netmask: netmask
          android-packages:
          - android-packages
          - android-packages
        referral_reward_bytes: 1.4658129805029452
        premium_data_bytes: 6.027456183070403
      properties:
        captive_portal:
          items:
            $ref: '#/components/schemas/GetClientConfig_200_Response_captive_portal'
          type: array
        denylist:
          items:
            $ref: '#/components/schemas/GetClientConfig_200_Response_denylist'
          type: array
        premium_data_bytes:
          type: number
        referral_reward_bytes:
          type: number
      required:
      - captive_portal
      - denylist
      - premium_data_bytes
      - referral_reward_bytes
      type: object
    GetSourceDevice_200_Response:
      example:
        created: created
        locale: locale
        type: type
        enabled: true
        waitlist_enabled: true
        install_id: install_id
        warp_enabled: true
        fcm_token: fcm_token
        name: name
        tos: tos
        model: model
        id: id
        place: 0.8008281904610115
        config:
          peers:
          - public_key: public_key
            endpoint:
              v6: v6
              host: host
              v4: v4
          - public_key: public_key
            endpoint:
              v6: v6
              host: host
              v4: v4
          services:
            http_proxy: http_proxy
          interface:
            addresses:
              v6: v6
              v4: v4
          client_id: client_id
        updated: updated
        account:
          license: license
          referral_count: 1.4658129805029452
          account_type: account_type
          role: role
          referral_renewal_countdown: 5.962133916683182
          created: created
          quota: 6.027456183070403
          usage: 5.637376656633329
          warp_plus: true
          premium_data: 0.8008281904610115
          id: id
          updated: updated
        key: key
      properties:
        account:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_account'
        config:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_config'
        created:
          type: string
        enabled:
          type: boolean
        fcm_token:
          type: string
        id:
          type: string
        install_id:
          type: string
        key:
          type: string
        locale:
          type: string
        model:
          type: string
        name:
          type: string
        place:
          type: number
        tos:
          type: string
        type:
          type: string
        updated:
          type: string
        waitlist_enabled:
          type: boolean
        warp_enabled:
          type: boolean
      required:
      - account
      - config
      - created
      - enabled
      - fcm_token
      - id
      - install_id
      - key
      - locale
      - model
      - name
      - place
      - tos
      - type
      - updated
      - waitlist_enabled
      - warp_enabled
      type: object
    Register_200_Response:
      example:
        created: created
        locale: locale
        type: type
        enabled: true
        token: token
        waitlist_enabled: true
        install_id: install_id
        warp_enabled: true
        fcm_token: fcm_token
        name: name
        tos: tos
        model: model
        id: id
        place: 2.3021358869347655
        config:
          peers:
          - public_key: public_key
            endpoint:
              v6: v6
              host: host
              v4: v4
          - public_key: public_key
            endpoint:
              v6: v6
              host: host
              v4: v4
          services:
            http_proxy: http_proxy
          interface:
            addresses:
              v6: v6
              v4: v4
          client_id: client_id
        updated: updated
        account:
          license: license
          referral_count: 1.4658129805029452
          account_type: account_type
          role: role
          referral_renewal_countdown: 5.962133916683182
          created: created
          quota: 6.027456183070403
          usage: 5.637376656633329
          warp_plus: true
          premium_data: 0.8008281904610115
          id: id
          updated: updated
        key: key
      properties:
        account:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_account'
        config:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_config'
        created:
          type: string
        enabled:
          type: boolean
        fcm_token:
          type: string
        id:
          type: string
        install_id:
          type: string
        key:
          type: string
        locale:
          type: string
        model:
          type: string
        name:
          type: string
        place:
          type: number
        token:
          type: string
        tos:
          type: string
        type:
          type: string
        updated:
          type: string
        waitlist_enabled:
          type: boolean
        warp_enabled:
          type: boolean
      required:
      - account
      - config
      - created
      - enabled
      - fcm_token
      - id
      - install_id
      - key
      - locale
      - model
      - name
      - place
      - token
      - tos
      - type
      - updated
      - waitlist_enabled
      - warp_enabled
      type: object
    Register_Request:
      properties:
        fcm_token:
          type: string
        install_id:
          type: string
        key:
          type: string
        locale:
          type: string
        model:
          type: string
        tos:
          type: string
        type:
          type: string
      required:
      - fcm_token
      - install_id
      - key
      - locale
      - model
      - tos
      - type
      type: object
    ResetAccountLicense_200_Response:
      example:
        license: license
      properties:
        license:
          type: string
      required:
      - license
      type: object
    UpdateAccount_200_Response:
      example:
        referral_count: 1.4658129805029452
        role: role
        referral_renewal_countdown: 5.962133916683182
        created: created
        quota: 6.027456183070403
        warp_plus: true
        premium_data: 0.8008281904610115
        id: id
        updated: updated
      properties:
        created:
          type: string
        id:
          type: string
        premium_data:
          type: number
        quota:
          type: number
        referral_count:
          type: number
        referral_renewal_countdown:
          type: number
        role:
          type: string
        updated:
          type: string
        warp_plus:
          type: boolean
      required:
      - created
      - id
      - premium_data
      - quota
      - referral_count
      - referral_renewal_countdown
      - role
      - updated
      - warp_plus
      type: object
    UpdateAccount_Request:
      properties:
        license:
          type: string
      required:
      - license
      type: object
    UpdateBoundDevice_200_Response:
      example:
        role: role
        created: created
        name: name
        active: true
        model: model
        id: id
        type: type
        activated: activated
      properties:
        activated:
          type: string
        active:
          type: boolean
        created:
          type: string
        id:
          type: string
        model:
          type: string
        name:
          type: string
        role:
          type: string
        type:
          type: string
      required:
      - activated
      - active
      - created
      - id
      - model
      - role
      - type
      type: object
    UpdateBoundDevice_Request:
      properties:
        active:
          type: boolean
        name:
          type: string
      type: object
    UpdateSourceDevice_200_Response:
      example:
        created: created
        locale: locale
        type: type
        enabled: true
        waitlist_enabled: true
        install_id: install_id
        warp_enabled: true
        fcm_token: fcm_token
        name: name
        tos: tos
        model: model
        id: id
        place: 5.637376656633329
        config:
          peers:
          - public_key: public_key
            endpoint:
              v6: v6
              host: host
              v4: v4
          - public_key: public_key
            endpoint:
              v6: v6
              host: host
              v4: v4
          services:
            http_proxy: http_proxy
          interface:
            addresses:
              v6: v6
              v4: v4
          client_id: client_id
        updated: updated
        account:
          license: license
          referral_count: 1.4658129805029452
          account_type: account_type
          role: role
          referral_renewal_countdown: 5.962133916683182
          created: created
          quota: 6.027456183070403
          warp_plus: true
          premium_data: 0.8008281904610115
          id: id
          updated: updated
        key: key
      properties:
        account:
          $ref: '#/components/schemas/UpdateSourceDevice_200_Response_account'
        config:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_config'
        created:
          type: string
        enabled:
          type: boolean
        fcm_token:
          type: string
        id:
          type: string
        install_id:
          type: string
        key:
          type: string
        locale:
          type: string
        model:
          type: string
        name:
          type: string
        place:
          type: number
        tos:
          type: string
        type:
          type: string
        updated:
          type: string
        waitlist_enabled:
          type: boolean
        warp_enabled:
          type: boolean
      required:
      - account
      - config
      - created
      - enabled
      - fcm_token
      - id
      - install_id
      - key
      - locale
      - model
      - name
      - place
      - tos
      - type
      - updated
      - waitlist_enabled
      - warp_enabled
      type: object
    UpdateSourceDevice_Request:
      properties:
        key:
          type: string
      required:
      - key
      type: object
    GetClientConfig_200_Response_networks:
      example:
        address: address
      properties:
        address:
          type: string
      required:
      - address
      type: object
    GetClientConfig_200_Response_captive_portal:
      example:
        name: name
        networks:
        - address: address
        - address: address
      properties:
        name:
          type: string
        networks:
          items:
            $ref: '#/components/schemas/GetClientConfig_200_Response_networks'
          type: array
      required:
      - name
      - networks
      type: object
    GetClientConfig_200_Response_networks_1_v4:
      example:
        address: address
        netmask: netmask
      properties:
        address:
          type: string
        netmask:
          type: string
      required:
      - address
      - netmask
      type: object
    GetClientConfig_200_Response_networks_1_v6:
      example:
        address: address
        prefix: 0.8008281904610115
      properties:
        address:
          type: string
        prefix:
          type: number
      required:
      - address
      - prefix
      type: object
    GetClientConfig_200_Response_networks_1:
      example:
        v6:
        - address: address
          prefix: 0.8008281904610115
        - address: address
          prefix: 0.8008281904610115
        v4:
        - address: address
          netmask: netmask
        - address: address
          netmask: netmask
      properties:
        v4:
          items:
            $ref: '#/components/schemas/GetClientConfig_200_Response_networks_1_v4'
          type: array
        v6:
          items:
            $ref: '#/components/schemas/GetClientConfig_200_Response_networks_1_v6'
          type: array
      required:
      - v4
      - v6
      type: object
    GetClientConfig_200_Response_denylist:
      example:
        visible: true
        name: name
        networks:
          v6:
          - address: address
            prefix: 0.8008281904610115
          - address: address
            prefix: 0.8008281904610115
          v4:
          - address: address
            netmask: netmask
          - address: address
            netmask: netmask
        android-packages:
        - android-packages
        - android-packages
      properties:
        android-packages:
          items:
            type: string
          type: array
        name:
          type: string
        networks:
          $ref: '#/components/schemas/GetClientConfig_200_Response_networks_1'
        visible:
          type: boolean
      required:
      - name
      - visible
      type: object
    GetSourceDevice_200_Response_account:
      example:
        license: license
        referral_count: 1.4658129805029452
        account_type: account_type
        role: role
        referral_renewal_countdown: 5.962133916683182
        created: created
        quota: 6.027456183070403
        usage: 5.637376656633329
        warp_plus: true
        premium_data: 0.8008281904610115
        id: id
        updated: updated
      properties:
        account_type:
          type: string
        created:
          type: string
        id:
          type: string
        license:
          type: string
        premium_data:
          type: number
        quota:
          type: number
        referral_count:
          type: number
        referral_renewal_countdown:
          type: number
        role:
          type: string
        updated:
          type: string
        usage:
          type: number
        warp_plus:
          type: boolean
      required:
      - account_type
      - created
      - id
      - license
      - premium_data
      - quota
      - referral_count
      - referral_renewal_countdown
      - role
      - updated
      - usage
      - warp_plus
      type: object
    GetSourceDevice_200_Response_config_interface_addresses:
      example:
        v6: v6
        v4: v4
      properties:
        v4:
          type: string
        v6:
          type: string
      required:
      - v4
      - v6
      type: object
    GetSourceDevice_200_Response_config_interface:
      example:
        addresses:
          v6: v6
          v4: v4
      properties:
        addresses:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_config_interface_addresses'
      required:
      - addresses
      type: object
    GetSourceDevice_200_Response_config_endpoint:
      example:
        v6: v6
        host: host
        v4: v4
      properties:
        host:
          type: string
        v4:
          type: string
        v6:
          type: string
      required:
      - host
      - v4
      - v6
      type: object
    GetSourceDevice_200_Response_config_peers:
      example:
        public_key: public_key
        endpoint:
          v6: v6
          host: host
          v4: v4
      properties:
        endpoint:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_config_endpoint'
        public_key:
          type: string
      required:
      - endpoint
      - public_key
      type: object
    GetSourceDevice_200_Response_config_services:
      example:
        http_proxy: http_proxy
      properties:
        http_proxy:
          type: string
      required:
      - http_proxy
      type: object
    GetSourceDevice_200_Response_config:
      example:
        peers:
        - public_key: public_key
          endpoint:
            v6: v6
            host: host
            v4: v4
        - public_key: public_key
          endpoint:
            v6: v6
            host: host
            v4: v4
        services:
          http_proxy: http_proxy
        interface:
          addresses:
            v6: v6
            v4: v4
        client_id: client_id
      properties:
        client_id:
          type: string
        interface:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_config_interface'
        peers:
          items:
            $ref: '#/components/schemas/GetSourceDevice_200_Response_config_peers'
          type: array
        services:
          $ref: '#/components/schemas/GetSourceDevice_200_Response_config_services'
      required:
      - client_id
      - interface
      - peers
      - services
      type: object
    UpdateSourceDevice_200_Response_account:
      example:
        license: license
        referral_count: 1.4658129805029452
        account_type: account_type
        role: role
        referral_renewal_countdown: 5.962133916683182
        created: created
        quota: 6.027456183070403
        warp_plus: true
        premium_data: 0.8008281904610115
        id: id
        updated: updated
      properties:
        account_type:
          type: string
        created:
          type: string
        id:
          type: string
        license:
          type: string
        premium_data:
          type: number
        quota:
          type: number
        referral_count:
          type: number
        referral_renewal_countdown:
          type: number
        role:
          type: string
        updated:
          type: string
        warp_plus:
          type: boolean
      required:
      - account_type
      - created
      - id
      - license
      - premium_data
      - quota
      - referral_count
      - referral_renewal_countdown
      - role
      - updated
      - warp_plus
      type: object
